### ISSUE TITLE
Precision of estimates for in-text numbers

### ISSUE THREAD

**Issue by gregmacfarlane** [byu-transpolab/uvx_headways#2]
Reviewer 1:

> On page 5, “headway is 4.649 minutes”. Consider if there might be a better way to present this data. Thousanths of a minute may be a bit uncomon.

**Comment by gregmacfarlane** [comment]
I definitely want to use the same precision that we have in the table. So, if we change this we need to change the table as well.

**Comment by TranspoShef** [comment]
I like your suggestion of parenthetically including 4 minutes and 39 seconds.

**Comment by gregmacfarlane** [comment]
Closed in 48986a4c
